repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^backend/
      - id: ruff-format
        files: ^backend/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        files: ^backend/
        additional_dependencies:
          [
            "types-requests",
            "types-python-dateutil",
            "types-sqlalchemy",
            "sqlalchemy[mypy]",
            "pydantic",
            "types-redis",
            "types-passlib",
            "types-python-jose",
            "types-aiofiles",
            "types-pytz",
            "types-cachetools",
          ]
