plugins = sqlalchemy.ext.mypy.plugin

[mypy]
warn_unreachable = True
warn_no_return = True
warn_redundant_casts = True
warn_unused_configs = True
exclude = (?x)(
    \.git/.*
    | \.mypy_cache/.*
    | __pycache__/.*
    | build/.*
    | dist/.*
)
