"""Initial migration

Revision ID: 01afbfc26ab3
Revises:
Create Date: 2025-02-02 01:29:57.635743

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "01afbfc26ab3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
